### ISSUE TITLE
volume mapping caused failure

### ISSUE THREAD

**Issue by WhatAKitty** [cptactionhank/docker-atlassian-jira#50]
Hey, the /opt/atlassian/jira/logs directory owner changed from daemon:daemon to bin:bin after docker run:
![image](https://user-images.githubusercontent.com/4178729/30256795-d825b286-96df-11e7-812b-b91acadffe86.png)

there is the log the jira started:
```
jira_1                  | Using JIRA_HOME:       /var/atlassian/jira
jira_1                  | 
jira_1                  | Server startup logs are located in /opt/atlassian/jira/logs/catalina.out
jira_1                  | OpenJDK 64-Bit Server VM warning: Cannot open file /opt/atlassian/jira/logs/atlassian-jira-gc-2017-09-11_02-55-04.log due to Permission denied
jira_1                  | 
jira_1                  | java.util.logging.ErrorManager: 4
jira_1                  | java.io.FileNotFoundException: /opt/atlassian/jira/logs/catalina.2017-09-11.log (Permission denied)
jira_1                  |       at java.io.FileOutputStream.open0(Native Method)
jira_1                  |       at java.io.FileOutputStream.open(FileOutputStream.java:270)
jira_1                  |       at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
jira_1                  |       at org.apache.juli.FileHandler.openWriter(FileHandler.java:384)
jira_1                  |       at org.apache.juli.FileHandler.<init>(FileHandler.java:96)
jira_1                  |       at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:78)
jira_1                  |       at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:74)
jira_1                  |       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jira_1                  |       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
jira_1                  |       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
jira_1                  |       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
jira_1                  |       at java.lang.Class.newInstance(Class.java:442)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:563)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:506)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:309)
jira_1                  |       at java.util.logging.LogManager$3.run(LogManager.java:399)
jira_1                  |       at java.util.logging.LogManager$3.run(LogManager.java:396)
jira_1                  |       at java.security.AccessController.doPrivileged(Native Method)
jira_1                  |       at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
jira_1                  |       at java.util.logging.LogManager.access$800(LogManager.java:145)
jira_1                  |       at java.util.logging.LogManager$2.run(LogManager.java:345)
jira_1                  |       at java.security.AccessController.doPrivileged(Native Method)
jira_1                  |       at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
jira_1                  |       at java.util.logging.LogManager.getLogManager(LogManager.java:378)
jira_1                  |       at java.util.logging.Logger.demandLogger(Logger.java:448)
jira_1                  |       at java.util.logging.Logger.getLogger(Logger.java:502)
jira_1                  |       at org.apache.juli.logging.DirectJDKLog.<init>(DirectJDKLog.java:67)
jira_1                  |       at org.apache.juli.logging.DirectJDKLog.getInstance(DirectJDKLog.java:187)
jira_1                  |       at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:117)
jira_1                  |       at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:141)
jira_1                  |       at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:196)
jira_1                  |       at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:52)
jira_1                  | java.util.logging.ErrorManager: 4
jira_1                  | java.io.FileNotFoundException: /opt/atlassian/jira/logs/localhost.2017-09-11.log (Permission denied)
jira_1                  |       at java.io.FileOutputStream.open0(Native Method)
jira_1                  |       at java.io.FileOutputStream.open(FileOutputStream.java:270)
jira_1                  |       at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
jira_1                  |       at org.apache.juli.FileHandler.openWriter(FileHandler.java:384)
jira_1                  |       at org.apache.juli.FileHandler.<init>(FileHandler.java:96)
jira_1                  |       at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:78)
jira_1                  |       at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:74)
jira_1                  |       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jira_1                  |       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
jira_1                  |       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
jira_1                  |       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
jira_1                  |       at java.lang.Class.newInstance(Class.java:442)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:563)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:506)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:309)
jira_1                  |       at java.util.logging.LogManager$3.run(LogManager.java:399)
jira_1                  |       at java.util.logging.LogManager$3.run(LogManager.java:396)
jira_1                  |       at java.security.AccessController.doPrivileged(Native Method)
jira_1                  |       at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
jira_1                  |       at java.util.logging.LogManager.access$800(LogManager.java:145)
jira_1                  |       at java.util.logging.LogManager$2.run(LogManager.java:345)
jira_1                  |       at java.security.AccessController.doPrivileged(Native Method)
jira_1                  |       at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
jira_1                  |       at java.util.logging.LogManager.getLogManager(LogManager.java:378)
jira_1                  |       at java.util.logging.Logger.demandLogger(Logger.java:448)
jira_1                  |       at java.util.logging.Logger.getLogger(Logger.java:502)
jira_1                  |       at org.apache.juli.logging.DirectJDKLog.<init>(DirectJDKLog.java:67)
jira_1                  |       at org.apache.juli.logging.DirectJDKLog.getInstance(DirectJDKLog.java:187)
jira_1                  |       at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:117)
jira_1                  |       at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:141)
jira_1                  |       at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:196)
jira_1                  |       at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:52)
jira_1                  | java.util.logging.ErrorManager: 4
jira_1                  | java.io.FileNotFoundException: /opt/atlassian/jira/logs/manager.2017-09-11.log (Permission denied)
jira_1                  |       at java.io.FileOutputStream.open0(Native Method)
jira_1                  |       at java.io.FileOutputStream.open(FileOutputStream.java:270)
jira_1                  |       at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
jira_1                  |       at org.apache.juli.FileHandler.openWriter(FileHandler.java:384)
jira_1                  |       at org.apache.juli.FileHandler.<init>(FileHandler.java:96)
jira_1                  |       at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:78)
jira_1                  |       at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:74)
jira_1                  |       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jira_1                  |       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
jira_1                  |       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
jira_1                  |       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
jira_1                  |       at java.lang.Class.newInstance(Class.java:442)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:563)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:506)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:309)
jira_1                  |       at java.util.logging.LogManager$3.run(LogManager.java:399)
jira_1                  |       at java.util.logging.LogManager$3.run(LogManager.java:396)
jira_1                  |       at java.security.AccessController.doPrivileged(Native Method)
jira_1                  |       at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
jira_1                  |       at java.util.logging.LogManager.access$800(LogManager.java:145)
jira_1                  |       at java.util.logging.LogManager$2.run(LogManager.java:345)
jira_1                  |       at java.security.AccessController.doPrivileged(Native Method)
jira_1                  |       at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
jira_1                  |       at java.util.logging.LogManager.getLogManager(LogManager.java:378)
jira_1                  |       at java.util.logging.Logger.demandLogger(Logger.java:448)
jira_1                  |       at java.util.logging.Logger.getLogger(Logger.java:502)
jira_1                  |       at org.apache.juli.logging.DirectJDKLog.<init>(DirectJDKLog.java:67)
jira_1                  |       at org.apache.juli.logging.DirectJDKLog.getInstance(DirectJDKLog.java:187)
jira_1                  |       at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:117)
jira_1                  |       at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:141)
jira_1                  |       at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:196)
jira_1                  |       at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:52)
jira_1                  | java.util.logging.ErrorManager: 4
jira_1                  | java.io.FileNotFoundException: /opt/atlassian/jira/logs/host-manager.2017-09-11.log (Permission denied)
jira_1                  |       at java.io.FileOutputStream.open0(Native Method)
jira_1                  |       at java.io.FileOutputStream.open(FileOutputStream.java:270)
jira_1                  |       at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
jira_1                  |       at org.apache.juli.FileHandler.openWriter(FileHandler.java:384)
jira_1                  |       at org.apache.juli.FileHandler.<init>(FileHandler.java:96)
jira_1                  |       at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:78)
jira_1                  |       at org.apache.juli.AsyncFileHandler.<init>(AsyncFileHandler.java:74)
jira_1                  |       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jira_1                  |       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
jira_1                  |       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
jira_1                  |       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
jira_1                  |       at java.lang.Class.newInstance(Class.java:442)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:563)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:506)
jira_1                  |       at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:309)
jira_1                  |       at java.util.logging.LogManager$3.run(LogManager.java:399)
jira_1                  |       at java.util.logging.LogManager$3.run(LogManager.java:396)
jira_1                  |       at java.security.AccessController.doPrivileged(Native Method)
jira_1                  |       at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
jira_1                  |       at java.util.logging.LogManager.access$800(LogManager.java:145)
jira_1                  |       at java.util.logging.LogManager$2.run(LogManager.java:345)
jira_1                  |       at java.security.AccessController.doPrivileged(Native Method)
jira_1                  |       at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
jira_1                  |       at java.util.logging.LogManager.getLogManager(LogManager.java:378)
jira_1                  |       at java.util.logging.Logger.demandLogger(Logger.java:448)
jira_1                  |       at java.util.logging.Logger.getLogger(Logger.java:502)
jira_1                  |       at org.apache.juli.logging.DirectJDKLog.<init>(DirectJDKLog.java:67)
jira_1                  |       at org.apache.juli.logging.DirectJDKLog.getInstance(DirectJDKLog.java:187)
jira_1                  |       at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:117)
jira_1                  |       at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:141)
jira_1                  |       at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:196)
jira_1                  |       at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:52)
```

docker compose :
```
  jira:
    image: cptactionhank/atlassian-jira
    ports:
      - 15000:8080
    networks:
      - jira_net
      - ci_net
    volumes:
      - /var/jira/webapp:/var/atlassian/jira
      - /var/jira/logs:/opt/atlassian/jira/logs
```

**Comment by tperelle** [comment]
It is normal, in the container the user daemon corresponds to an UID 1.
Out of the container, on the hosts where the volume FS is, the UID 1 corresponds to a user named bin.
So, when then Jira container makes chown on FS with the user daemon, it appears with bin on the host.
