### ISSUE TITLE
corrupted postgresql-9.4.3.02.jar lib

### ISSUE THREAD

**Issue by ata-sql** [cptactionhank/docker-atlassian-jira#98]
Latest version (SD with jira 8.3.0) includes corrupted postges lib.
`23-Jul-2019 05:49:55.535 WARNING [localhost-startStop-1] org.apache.tomcat.util.scan.StandardJarScanner.processURLs Failed to scan [file:/opt/atlassian/jira/lib/postgresql-9.4.3.02.jar] from classloader hierarchy
 java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:196)
	at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:65)
	at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:49)
	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:374)
	at org.apache.tomcat.util.scan.StandardJarScanner.processURLs(StandardJarScanner.java:309)
	at org.apache.tomcat.util.scan.StandardJarScanner.doScanClassPath(StandardJarScanner.java:266)
	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:229)
	at org.apache.jasper.servlet.TldScanner.scanJars(TldScanner.java:262)
	at org.apache.jasper.servlet.TldScanner.scan(TldScanner.java:104)
	at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:101)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5225)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

It has no content:
`docker exec jira ls -Aal /opt/atlassian/jira/lib/postgresql-9.4.3.02.jar
-rw-r--r--    1 root     root           345 Jul 23 00:16 /opt/atlassian/jira/lib/postgresql-9.4.3.02.jar
`

In fact is has some text content:
```
docker exec jira cat /opt/atlassian/jira/lib/postgresql-9.4.3.02.jar
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
```

Image ID: 50199b9d0dae

**Comment by ata-sql** [comment]
newer version (8.3.1) suffers similar problem:
`
05-Aug-2019 10:24:55.314 WARNING [localhost-startStop-1] org.apache.tomcat.util.scan.StandardJarScanner.processURLs Failed to scan [file:/opt/atlassian/jira/lib/postgresql-9.4.3.12.jar] from classloader hierarchy
 java.util.zip.ZipException: error in opening zip file
`

**Comment by ata-sql** [comment]
newer version (8.3.2) suffers similar problem:
`
19-Aug-2019 10:18:23.159 WARNING [localhost-startStop-1] org.apache.tomcat.util.scan.StandardJarScanner.processURLs Failed to scan [file:/opt/atlassian/jira/lib/postgresql-9.4.3.22.jar] from classloader hierarchy
 java.util.zip.ZipException: error in opening zip file
`
Does anyone plan to do sth with it?

**Comment by ata-sql** [comment]
`
bash-4.4$ ls -Aal /opt/atlassian/jira/lib/ | grep postg
-rw-r--r--    1 root     root        680445 Aug 13 15:56 postgresql-9.4.1212.jar
-rw-r--r--    1 root     root           345 Aug 14 00:10 postgresql-9.4.3.22.jar
`
Seems that this file shouldn't exists. Manual removing fixes problem.
